const APPOINTMENT_VIEW_BACK = 'APPOINTMENT_VIEW_BACK';
const EDIT_APPOINTMENT_EVENT = 'EDIT_APPOINTMENT_EVENT';
const CLOSE_APPOINTMENT_MODAL = 'CLOSE_APPOINTMENT_MODAL';
const EDIT_APPOINTMENT_STATUS = 'EDIT_APPOINTMENT_STATUS';
const REQUEST_APPOINTMENT_CHANGE = 'REQUEST_APPOINTMENT_CHANGE';
const APPOINTMENT_RECORD_UPDATED = 'APPOINTMENT_RECORD_UPDATED';

export {
  EDIT_APPOINTMENT_STATUS,
  APPOINTMENT_VIEW_BACK,
  EDIT_APPOINTMENT_EVENT,
  CLOSE_APPOINTMENT_MODAL,
  REQUEST_APPOINTMENT_CHANGE,
  APPOINTMENT_RECORD_UPDATED
}
