const POPULATE_DOCTOR_PROFILE = 'POPULATE_DOCTOR_PROFILE';
const DOCTOR_PROFILE_ERROR = 'DOCTOR_PROFILE_ERROR';
const RESET_DOCTOR_PROFILE = 'RESET_DOCTOR_PROFILE';

export {
  DOCTOR_PROFILE_ERROR,
  RESET_DOCTOR_PROFILE,
  POPULATE_DOCTOR_PROFILE
}
