const POPULATE_HOSPITAL_PROFILE = 'POPULATE_HOSPITAL_PROFILE';
const HOSPITAL_PROFILE_ERROR = 'HOSPITAL_PROFILE_ERROR';
const RESET_HOSPITAL_PROFILE = 'RESET_HOSPITAL_PROFILE';

export {
  HOSPITAL_PROFILE_ERROR,
  RESET_HOSPITAL_PROFILE,
  POPULATE_HOSPITAL_PROFILE
}
