import {
  CDN_URI
} from './resources'

const CONNECTED = 'CONNECTED';
const CHANGE_VIEW = 'CHANGE_VIEW';
const DISCONNECTED = 'DISCONNECTED';
const EXIT_PATIENT_VIEW = 'EXIT_PATIENT_VIEW';
const PATIENT_FILES_DROPPED = 'PATIENT_FILES_DROPPED'
const PATIENT_FILES_UPLOADED = 'PATIENT_FILES_UPLOADED'
const PATIENT_FILE_REMOVED = 'PATIENT_FILE_REMOVED'
const PATIENT_FILES_UPLOADING = 'PATIENT_FILES_UPLOADING';
const CANCEL_FILE_UPLOAD = 'CANCEL_FILE_UPLOAD';
const PATIENT_TAB_SELECTED = 'PATIENT_TAB_SELECTED';

export {
  CONNECTED,
  CHANGE_VIEW,
  DISCONNECTED,
  EXIT_PATIENT_VIEW,
  PATIENT_FILES_DROPPED,
  PATIENT_FILES_UPLOADED,
  PATIENT_FILE_REMOVED,
  PATIENT_FILES_UPLOADING,
  CANCEL_FILE_UPLOAD,
  PATIENT_TAB_SELECTED,
  CDN_URI
}
