import {
  CDN_URI
} from './resources'

const CONNECTED = 'CONNECTED';
const CHANGE_VIEW = 'CHANGE_VIEW';
const DISCONNECTED = 'DISCONNECTED';
const EXIT_PATIENT_VIEW = 'EXIT_PATIENT_VIEW';
const PATIENT_FILES_DROPPED = 'PATIENT_FILES_DROPPED'
const PATIENT_FILES_UPLOADED = 'PATIENT_FILES_UPLOADED'
const PATIENT_FILE_REMOVED = 'PATIENT_FILE_REMOVED'
const PATIENT_FILES_UPLOADING = 'PATIENT_FILES_UPLOADING';
const CANCEL_FILE_UPLOAD = 'CANCEL_FILE_UPLOAD';
const PATIENT_TAB_SELECTED = 'PATIENT_TAB_SELECTED';
const SEARCH_INPUT_UPDATE = 'SEARCH_INPUT_UPDATE';
const PATIENTS_VIEW_RESET = 'PATIENTS_VIEW_RESET';
const EDIT_APPOINTMENT_STATUS = 'EDIT_APPOINTMENT_STATUS';
const REQUEST_APPOINTMENT_CHANGE = 'REQUEST_APPOINTMENT_CHANGE';
const APPOINTMENT_RECORD_UPDATED = 'APPOINTMENT_RECORD_UPDATED'
const VIEW_APPOINTMENT = 'VIEW_APPOINTMENT';
const APPOINTMENT_VIEW_BACK = 'APPOINTMENT_VIEW_BACK';
const EDIT_APPOINTMENT_EVENT = 'EDIT_APPOINTMENT_EVENT';

export {
  CONNECTED,
  CHANGE_VIEW,
  DISCONNECTED,
  EXIT_PATIENT_VIEW,
  EDIT_APPOINTMENT_EVENT,
  PATIENT_FILES_DROPPED,
  PATIENT_FILES_UPLOADED,
  PATIENT_FILE_REMOVED,
  VIEW_APPOINTMENT,
  APPOINTMENT_VIEW_BACK,
  PATIENT_FILES_UPLOADING,
  CANCEL_FILE_UPLOAD,
  EDIT_APPOINTMENT_STATUS,
  APPOINTMENT_RECORD_UPDATED,
  REQUEST_APPOINTMENT_CHANGE,
  PATIENT_TAB_SELECTED,
  SEARCH_INPUT_UPDATE,
  PATIENTS_VIEW_RESET,
  CDN_URI
}
