const TOGGLE_PROXIMITY_SEARCH = 'TOGGLE_PROXIMITY_SEARCH';
const UPDATE_GEO_COORDINATES = 'UPDATE_GEO_COORDINATES';
const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';

export {
  UPDATE_GEO_COORDINATES,
  TOGGLE_PROXIMITY_SEARCH,
  UPDATE_SEARCH_RESULTS
}
