const MedicineSpecialties = [
  'Radiology-Diagnostic',
  'Psychiatry',
  'Pediatrics',
  'Anesthesiology',
  'Orthopaedic Surgery',
  'Internal Medicine',
  'Medical Genetics',
  'Pathology-Anatomic & Clinical',
  'Radiology-Diagnostic',
  'Internal Medicine',
  'Pathology-Anatomic & Clinical',
  'Psychiatry',
  'Pediatrics',
  'Neurology',
  'Allergy & Immunology',
  'Internal Medicine',
  'Neurology',
  'Thoracic Surgery',
  'Plastic Surgery',
  'Anesthesiology',
  'Internal Medicine',
  'Pathology-Anatomic & Clinical',
  'Dermatology',
  'Pediatrics',
  'Internal Medicine',
  'Neurological Surgery',
  'Radiology-Diagnostic',
  'Obstetrics & Gynecology',
  'Orthopaedic Surgery',
  'Pathology-Anatomic & Clinical',
  'Psychiatry',
  'Internal Medicine',
  'Family Medicine',
  'Internal Medicine',
  'Family Practice',
  'Psychiatry',
  'Orthopaedic Surgery',
  'Plastic Surgery',
  'Surgery-General',
  'Internal Medicine',
  'Pathology-Anatomic & Clinical',
  'Internal Medicine',
  'Internal Medicine',
  'Internal Medicine',
  'Pathology-Anatomic & Clinical',
  'Emergency Medicine',
  'Preventive Medicine',
  'Medical Genetics',
  'Radiology-Diagnostic',
  'Orthopaedic Surgery',
  'Pediatrics',
  'Internal Medicine',
  'Neurology',
  'Physical Medicine & Rehabilitation',
  'Pathology-Anatomic & Clinical',
  'Radiology-Diagnostic',
  'Radiology-Diagnostic',
  'Anesthesiology',
  'Internal Medicine',
  'Ophthalmology',
  'Orthopaedic Surgery',
  'Orthopaedic Surgery',
  'Orthopaedic Surgery',
  'Otolaryngology',
  'Anesthesiology',
  'Neurology',
  'Physical Medicine & Rehabilitation',
  'Anesthesiology',
  'Pediatrics',
  'Pediatrics',
  'Emergency Medicine',
  'Pediatrics',
  'Pediatrics',
  'Pediatrics',
  'Pediatrics',
  'Pediatrics',
  'Pediatrics',
  'Orthopaedic Surgery',
  'Otolaryngology',
  'Pathology',
  'Pediatrics',
  'Radiology-Diagnostic',
  'Pediatrics',
  'Pediatrics',
  'Surgery-General',
  'Pediatrics',
  'Urology',
  'Dermatology',
  'Internal Medicine',
  'Internal Medicine',
  'Internal Medicine',
  'Physical Medicine & Rehabilitation',
  'Emergency Medicine',
  'Family Medicine',
  'Internal Medicine',
  'Physical Medicine & Rehabilitation',
  'Surgery-General',
  'Thoracic Surgery',
  'Internal Medicine',
  'Radiology-Diagnostic',
  'Surgery-General'
]

module.exports = MedicineSpecialties;
